# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
