# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
