# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=b'null', upload_to=b'imgs/'),
        ),
    ]
