# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_auto_20161218_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(default='74.0059'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lon',
            field=models.FloatField(default='40.7128'),
        ),
    ]
