# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('micro', '0003_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=256)),
                ('text', models.CharField(default=b'', max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name=b'date_posted')),
                ('votes', models.BigIntegerField(default=0)),
                ('url', models.URLField(default=b'')),
                ('latitude', models.FloatField(default=b'40.7128')),
                ('longtitude', models.FloatField(default=b'74.0059')),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
