# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0005_auto_20161217_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
