# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0006_auto_20161217_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
