# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(default=b'74.0059'),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(default=b'40.7128'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
