# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_auto_20161218_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
