# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 01:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0003_auto_20161218_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default=b''),
        ),
    ]
